Create a numpy array with filling random values, and shape of array
should be (12,5), after that manipulate the value of last row.
For e.g. let’s consider this is your last row [41,52,63,96,85], you will
update this line like this [1,2,3,4,5]

In [18]:
import numpy as np
arr1 = np.random.randint(1,51,60).reshape(12,5)

In [19]:

arr1

array([[43, 29, 30, 21,  7],
       [40, 40, 31,  6, 15],
       [ 8, 30, 25, 48, 19],
       [ 8, 11, 40,  7, 35],
       [24,  3, 17, 30, 33],
       [ 8, 48,  5, 17,  2],
       [38, 12, 38,  3, 47],
       [20,  4, 29, 11, 11],
       [ 5,  3, 47, 27, 13],
       [25, 21, 19, 32, 39],
       [10,  2, 38, 45, 25],
       [ 4, 20, 26, 15, 39]])

In [20]:
arr1.ndim

2

In [27]:
arr1[11]  # last row

array([ 4, 20, 26, 15, 39])

In [29]:
arr1[11] = [1,2,3,4,5]  # changing last row

In [30]:
arr1

array([[43, 29, 30, 21,  7],
       [40, 40, 31,  6, 15],
       [ 8, 30, 25, 48, 19],
       [ 8, 11, 40,  7, 35],
       [24,  3, 17, 30, 33],
       [ 8, 48,  5, 17,  2],
       [38, 12, 38,  3, 47],
       [20,  4, 29, 11, 11],
       [ 5,  3, 47, 27, 13],
       [25, 21, 19, 32, 39],
       [10,  2, 38, 45, 25],
       [ 1,  2,  3,  4,  5]])

Write a python function to find the minimum and maximum elements
in each and every row of numpy array, and create numpy array with
filling random integer value, and shape of array should be (12,5),
For e.g. I took first row from
2D array [21,4,3,62,52,1] so 1 is minimum and 52 is maximum in this
row. So your python function should return this output for each and
every row.

In [36]:
def max_n_min(arr):
    for i in range(len(arr)):
        j=0
        max=arr[i][j]
        min=arr[i][j]
        for num in arr[i]:
            if arr[i][j]>max:
                max=arr[i][j]
            if arr[i][j]<min:
                min=arr[i][j]
            j+=1
        print(f'For row {i+1}, max element : {max}  and min element : {min}' )

arr2 = np.random.randint(1,51,60).reshape(12,5)
arr2


array([[ 8, 46, 42, 13, 39],
       [ 6, 26, 12,  2, 48],
       [ 1, 38, 23,  2, 35],
       [47, 29, 25,  1,  5],
       [36, 33,  8,  8, 23],
       [17,  1, 25, 19,  8],
       [46, 47, 29, 39, 49],
       [16, 46, 40,  4, 20],
       [37,  5, 39, 31, 22],
       [44, 28, 26, 11,  3],
       [ 7,  6, 33, 36, 45],
       [10, 43, 12,  3, 13]])

In [37]:
max_n_min(arr2)

For row 1, max element : 46  and min element : 8
For row 2, max element : 48  and min element : 2
For row 3, max element : 38  and min element : 1
For row 4, max element : 47  and min element : 1
For row 5, max element : 36  and min element : 8
For row 6, max element : 25  and min element : 1
For row 7, max element : 49  and min element : 29
For row 8, max element : 46  and min element : 4
For row 9, max element : 39  and min element : 5
For row 10, max element : 44  and min element : 3
For row 11, max element : 45  and min element : 6
For row 12, max element : 43  and min element : 3
