 Create a numpy array with filling random values, and shape of array 
should be (12,5), and pass this array from a user-defined function, and 
function should be able to return average, minimum, maximum, and 
no. of evens in your last row. 
For e.g. consider this is last row [41,52,63,96,85], 
Output:
Average -> 67.4
Minimum -> 41
Maximum -> 96
No. of evens -> 2


In [18]:
import numpy as np

def function(arr):
    tot_sum=0 
    max=arr[len(arr) -1][0]
    min=arr[len(arr) -1][0]
    for i in arr[len(arr) -1]:
        tot_sum += i
        if i > max :
            max = i
        if i < min:
            min = i
    avg = tot_sum/5
    print(f'Average : {avg} , Maximum Element : {max} , Minimum Element : {min}')  

arr0 = np.random.randint(1,61,60)
arr0
arr1 = arr0.reshape(12,5)
arr1




        


array([[36, 43, 34,  3, 33],
       [24, 38, 31, 36, 58],
       [30, 23, 10, 17, 50],
       [ 4, 27, 23,  1, 19],
       [14, 33, 32, 24, 56],
       [ 1, 17, 11, 48, 24],
       [55,  5, 33, 39, 49],
       [ 5, 12, 34, 19, 45],
       [21, 14, 20, 42, 31],
       [17, 14, 48, 12, 54],
       [60, 49, 38, 30, 53],
       [36,  7, 37, 24,  2]])

In [19]:
function(arr1)

Average : 21.2 , Maximum Element : 37 , Minimum Element : 2


 Let’s consider we have an array, e.g.
[[1 2 3 ],
[4 5 6 ],
[7 8 9 ]]
And apply slicing techniques to get reversed order elements of all the rows, 
like this -> [[3 2 1],
 [6 5 4],
 [9 8 7]]


In [ ]:
import numpy as np
arr  = np.array( [[1,2,3] , [4,5,6] , [7,8,9]] )
arr



array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
arr[: , ::-1]

array([[3, 2, 1],
       [6, 5, 4],
       [9, 8, 7]])